services:
  - type: web
    name: yolo-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
